--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VBackpack
build-by-default: true
branches:
- main
projects:
  VBackpack:
    path: ""
    lint:
      phpstan: false
      syntaxError: false
    libs:
      - src: Muqsit/InvMenu/InvMenu
        version: ^4.6.5
        branch: "pm5"
...
