name: VBackpack
api: 5.0.0
author: VennVDev
main: vennv\vbackpack\VBackpack
version: 1.0.1

commands:
    vbackpack:
        description: VBackpack command
        usage: /vbackpack give <player> <type> <amount>
        aliases: [vbp]
        permission: vbackpack.command
        permission-message: You don't have permission to use this command.

permissions:
    vbackpack.command:
        description: VBackpack command permission
        default: op
